title: Portable Dotfiles
description: dotfiles for one-time shell sessions

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

include:
  - .bashrc
  - .inputrc
  - .screenrc
  - .tmux.conf
  - .vimrc
  - .zshrc

exclude:
  - UNLICENSE
