#!/usr/bin/env perl

$ENV{LATEXMK_ENGINE} //= '';
if ($ENV{LATEXMK_ENGINE} eq 'uplatex') {
  $latex = 'uplatex -kanji=utf8 -synctex=1 -file-line-error -interaction=nonstopmode';
  $dvipdf ='dvipdfmx %O -o %D %S';
  $bibtex = 'upbibtex';
  $makeindex = 'upmendex %O -o %D %S';
  $pdf_mode = 3;
} elsif ($ENV{LATEXMK_ENGINE} eq 'platex') {
  $latex = 'platex -kanji=utf8 -synctex=1 -file-line-error -interaction=nonstopmode';
  $dvipdf ='dvipdfmx %O -o %D %S';
  $bibtex = 'pbibtex';
  $makeindex = 'mendex %O -o %D %S';
  $pdf_mode = 3;
} else {
  $pdflatex = 'pdflatex -synctex=1 -file-line-error -interaction=nonstopmode';
  $pdf_mode = 1;
}

$biber = 'biber -u -U --output_safechars';
$max_repeat = 5;

if ($^O eq 'linux') {
  $pdf_previewer = 'xdg-open';
} elsif ($^O eq 'darwin') {
  if (-d '/Applications/Skim.app') {
    $pdf_previewer = 'open -ga /Applications/Skim.app'
  } else {
    $pdf_previewer = 'open -g';
  }
}
