" set PATH
let s:path=system("$SHELL -ic 'echo PATH=$PATH'")
let $PATH=matchstr(s:path, 'PATH=\zs.\{-}\ze\n')

set cmdheight=1
set cursorline
set confirm

if has('gui_macvim')
  set columns=132
  set lines=43
  set guifont=Fira\ Code:h12
  set guitablabel=%M%t
  set guioptions-=T
  set transparency=15
endif
