#!/bin/bash

cxx=

for n in "$@"; do
  case "$n" in
    --cxx) cxx=1 ;;
    *) ;;
  esac
done

echo "-isystem"
echo "@libc@"

if [[ -n "$cxx" ]]; then
  echo "-isystem"
  echo "@libcxx@"
fi

for flag in $NIX_CFLAGS_COMPILE; do
  echo "$flag"
done

for path in "@clang@"/lib/clang/*/include; do
  echo "-isystem"
  echo "$path"
  break
done
