" set PATH
let s:path=system("$SHELL -ic 'echo PATH=$PATH'")
let $PATH=matchstr(s:path, 'PATH=\zs.\{-}\ze\n')

set lines=40
set columns=120
set cmdheight=1
set cursorline
set guifont=Monospace\ 13
set guitablabel=%M%t
set guioptions-=T
set confirm
colorscheme molokai
