---
dotfiles:
  repo_url: https://github.com/midchildan/dotfiles
  archive_path: archive/main.tar.gz
  dest: ~/.config/dotfiles
proxy_env: &proxy_env
  http_proxy: &http_proxy
  https_proxy: &https_proxy
  ftp_proxy: &ftp_proxy
  no_proxy: &no_proxy 127.0.0.1,127.0.0.0/8,localhost,.local,.home.arpa,.test
  HTTP_PROXY: *http_proxy
  HTTPS_PROXY: *https_proxy
  FTP_PROXY: *ftp_proxy
  NO_PROXY: *no_proxy
nix_install_env:
  PATH: "{{ ansible_env.PATH }}:/usr/sbin"
