#!/usr/bin/env bash

# This hook is meant to be used in conjuction with git-deploy [1] to deploy
# dotfiles to a remote with a simple git push.
#
# [1] See home/.local/bin/git-deploy

# Sample Usage:
#
# The following commands would setup a remote repository which can be used to
# deploy dotfiles in "branch1" to a remote named "host1". After setup is
# complete, a simple "git push" would apply changes to your dotfiles and
# trigger the deployment script remotely.
#
#     $ git deploy -r -b branch1 host1 user@host1.example.com:.config/dotfiles
#     $ git push host1
#     $ ssh -t user@host1.example.com 'cd .config/dotfiles; ./setup.sh --init'


# XXX: The following is needed to ensure submodule updates run properly in the 
#      setup script.
unset GIT_DIR

# XXX: post-recieve hooks run from $GIT_DIR. See githooks(5) for details.
source ../setup.sh
