#!/usr/bin/env bash

# FIXME: Rethink the use of gitignore.io in favor of an offline solution. See
# https://github.com/toptal/gitignore.io/pull/494 for details.

main() {
  local selected="$( \
    curl -sSfL https://www.gitignore.io/api/list | tr , '\n' | fzf_or_abort +m )"
  curl -sSfL "https://www.gitignore.io/api/$selected"
}

abort() {
  local message="abort"
  [[ -n "$1" ]] && message="$1"
  printf "[%s:%s] %s\n" "${FUNCNAME[1]}" "${BASH_LINENO[0]}" "$message" >&2
  exit 1
}

fzf_or_abort() {
  fzf-tmux "$@" || abort "FZF selection canceled"
}

main
