name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  flake:
    strategy:
      matrix:
        runners: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.runners }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31.6.0
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - name: Check flake
        run: nix flake check
  nixos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31.6.0
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - name: Build NixOS configuration
        run: nix run '.#os' -- build -L --flake '.#ci' --print-build-logs
