name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Check flake
        run: nix flake check
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Check format
        run: |
          nix fmt
          git diff --exit-code
  home-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Build Home Manager configuration
        run: |
          nix-env -q # TODO: Remove. https://github.com/nix-community/home-manager/pull/3872
          nix run '.#home' -- build --flake '.#ci' --print-build-logs
  nixos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Build NixOS configuration
        run: nix run '.#os' -- build -L --flake '.#ci' --print-build-logs
  nix-darwin-amd64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Build nix-darwin configuration
        run: nix run '.#os' -- build -L --flake '.#ci-amd64' --print-build-logs
