name: Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Check flake
        run: nix flake check
  home-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
      - name: Build Home Manager configuration
        run: nix-build -A homeConfigurations.ci
  nixos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
      - name: Build NixOS configuration
        run: nix-build -A nixosConfigurations.ci.config.system.build.toplevel
  nix-darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
      - name: Build nix-darwin configuration
        run: nix-build -A darwinConfigurations.ci.system
