name: Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - name: Check flake
        run: nix flake check
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - name: Check format
        run: |
          nix fmt
          git diff --exit-code
  home-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - name: Build Home Manager configuration
        run: nix run '.#home' -- build --flake '.#ci'
  nixos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - name: Build NixOS configuration
        run: nix run '.#nixos' -- build -L --flake '.#ci'
  nix-darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - name: Build nix-darwin configuration
        run: nix run '.#darwin' -- build -L --flake '.#ci'
