#!/bin/bash

# Temporary installer script for fzf to be used until it's packaged in Debian.

# This script is intended to be run from vim-plug. If running manually,
# be sure to cd to the directory where fzf is cloned first.

main() {
  rm ~/.local/bin/fzf ~/.local/bin/fzf-tmux

  [[ -x /usr/bin/fzf ]] && return
  [[ -x /usr/local/bin/fzf ]] && return
  [[ -x ~/.nix-profile/bin/fzf ]] && return

  set -e

  local version="$(curl -sfL 'https://api.github.com/repos/junegunn/fzf-bin/releases/latest' \
    | grep tag_name \
    | cut -d : -f 2 \
    | cut -d '"' -f 2)"
  local os="$(uname -s | tr '[:upper:]' '[:lower:]' | tr -d '\n')"
  local arch="$(uname -m)"
  case "$arch" in
    *64) arch="amd64" ;;
    *86) arch="386" ;;
    armv5*) arch="arm5" ;;
    armv6*) arch="arm6" ;;
    armv7*) arch="arm7" ;;
    armv8*) arch="arm8" ;;
    *) return 1;;
  esac

  cd bin
  download "$version" "$os" "$arch" || return 1
  ln -s fzf ~/.local/bin
  ln -s fzf-tmux ~/.local/bin
}

download() {
  local version="$1"
  local os="$2"
  local arch="$3"
  local url="https://github.com/junegunn/fzf-bin/releases/download/${version}/fzf-${version}-${os}_${arch}.tgz"

  curl -sfL "$url" | tar xz
  [[ ! -f fzf ]] && return 1
  chmod +x fzf
}

main
